### ISSUE TITLE
could not clone submodules

### ISSUE THREAD

**Issue by master221** [tektoncd/catalog#312]
# Expected Behavior
git [submodule update --recursive --depth=1]
# Actual Behavior
 /ko-app/git-init -url https://mygerritserver.com/a/myrepo -revision FETCH_HEAD -refspec '+refs/heads/mybranch:refs/remotes/origin/mybranch' -path /workspace/output/ '-sslVerify=true' '-submodules=true' -depth 2
{"level":"info","ts":1589204144.3671,"caller":"git/git.go:136","msg":"Successfully cloned https://mygerritserver.com/a/myrepo @ 1b2e66bb27fce18743732918271213c701dbf900 (HEAD, origin/commit) in path /workspace/output/"}
{"level":"error","ts":1589204144.5016918,"caller":"git/git.go:41","msg":"**Error running git [submodule update --recursive --depth --depth=1]:** exit status 1\nfatal: depth --depth=2 is not a positive number
# Steps to Reproduce the Problem

1. Run task git-clone with default 'depth' parameter 
2.
3.

# Additional Info
using apiVersion: tekton.dev/v1beta1

task reference
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
      params:
        - name: revision
          value: FETCH_HEAD
        - name: refspec
          value: +refs/heads/mybranch:refs/remotes/origin/mybranch
        - name: url
          value: https://mygerritserver.com/a/myrepo

**Comment by jlpettersson** [comment]
I think this was solved by https://github.com/tektoncd/pipeline/pull/2602

**Comment by vdemeester** [comment]
/kind bug
@jlpettersson it is but it's not fixed on the image version used by the task :sweat_smile:
